### ISSUE TITLE
Deprecate library

### ISSUE THREAD

**Issue by dimaMachina** [mariansimecek/remark-mermaid-nextra#4]
Hi there,

I am the original creator of this remark plugin from [`@theguild/components`](https://github.com/the-guild-org/docs).

Starting from v2.8.0, Nextra uses [`@theguild/remark-mermaid`](https://www.npmjs.com/package/@theguild/remark-mermaid) mermaid react plugin agnostic that supports both dark/light themes.

I suggest you deprecate this library in favour of my maintained plugin.

**Comment by mariansimecek** [comment]
Thank you for awesome work. 

I made npm package deprecated and I will archive this repository
